require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe TiedsController do

  # This should return the minimal set of attributes required to create a valid
  # Tied. As you add validations to Tied, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TiedsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all tieds as @tieds" do
      tied = Tied.create! valid_attributes
      get :index, {}, valid_session
      assigns(:tieds).should eq([tied])
    end
  end

  describe "GET show" do
    it "assigns the requested tied as @tied" do
      tied = Tied.create! valid_attributes
      get :show, {:id => tied.to_param}, valid_session
      assigns(:tied).should eq(tied)
    end
  end

  describe "GET new" do
    it "assigns a new tied as @tied" do
      get :new, {}, valid_session
      assigns(:tied).should be_a_new(Tied)
    end
  end

  describe "GET edit" do
    it "assigns the requested tied as @tied" do
      tied = Tied.create! valid_attributes
      get :edit, {:id => tied.to_param}, valid_session
      assigns(:tied).should eq(tied)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Tied" do
        expect {
          post :create, {:tied => valid_attributes}, valid_session
        }.to change(Tied, :count).by(1)
      end

      it "assigns a newly created tied as @tied" do
        post :create, {:tied => valid_attributes}, valid_session
        assigns(:tied).should be_a(Tied)
        assigns(:tied).should be_persisted
      end

      it "redirects to the created tied" do
        post :create, {:tied => valid_attributes}, valid_session
        response.should redirect_to(Tied.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved tied as @tied" do
        # Trigger the behavior that occurs when invalid params are submitted
        Tied.any_instance.stub(:save).and_return(false)
        post :create, {:tied => {}}, valid_session
        assigns(:tied).should be_a_new(Tied)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Tied.any_instance.stub(:save).and_return(false)
        post :create, {:tied => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested tied" do
        tied = Tied.create! valid_attributes
        # Assuming there are no other tieds in the database, this
        # specifies that the Tied created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Tied.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => tied.to_param, :tied => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested tied as @tied" do
        tied = Tied.create! valid_attributes
        put :update, {:id => tied.to_param, :tied => valid_attributes}, valid_session
        assigns(:tied).should eq(tied)
      end

      it "redirects to the tied" do
        tied = Tied.create! valid_attributes
        put :update, {:id => tied.to_param, :tied => valid_attributes}, valid_session
        response.should redirect_to(tied)
      end
    end

    describe "with invalid params" do
      it "assigns the tied as @tied" do
        tied = Tied.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Tied.any_instance.stub(:save).and_return(false)
        put :update, {:id => tied.to_param, :tied => {}}, valid_session
        assigns(:tied).should eq(tied)
      end

      it "re-renders the 'edit' template" do
        tied = Tied.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Tied.any_instance.stub(:save).and_return(false)
        put :update, {:id => tied.to_param, :tied => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested tied" do
      tied = Tied.create! valid_attributes
      expect {
        delete :destroy, {:id => tied.to_param}, valid_session
      }.to change(Tied, :count).by(-1)
    end

    it "redirects to the tieds list" do
      tied = Tied.create! valid_attributes
      delete :destroy, {:id => tied.to_param}, valid_session
      response.should redirect_to(tieds_url)
    end
  end

end
