require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe VerifiedsController do

  # This should return the minimal set of attributes required to create a valid
  # Verified. As you add validations to Verified, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # VerifiedsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all verifieds as @verifieds" do
      verified = Verified.create! valid_attributes
      get :index, {}, valid_session
      assigns(:verifieds).should eq([verified])
    end
  end

  describe "GET show" do
    it "assigns the requested verified as @verified" do
      verified = Verified.create! valid_attributes
      get :show, {:id => verified.to_param}, valid_session
      assigns(:verified).should eq(verified)
    end
  end

  describe "GET new" do
    it "assigns a new verified as @verified" do
      get :new, {}, valid_session
      assigns(:verified).should be_a_new(Verified)
    end
  end

  describe "GET edit" do
    it "assigns the requested verified as @verified" do
      verified = Verified.create! valid_attributes
      get :edit, {:id => verified.to_param}, valid_session
      assigns(:verified).should eq(verified)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Verified" do
        expect {
          post :create, {:verified => valid_attributes}, valid_session
        }.to change(Verified, :count).by(1)
      end

      it "assigns a newly created verified as @verified" do
        post :create, {:verified => valid_attributes}, valid_session
        assigns(:verified).should be_a(Verified)
        assigns(:verified).should be_persisted
      end

      it "redirects to the created verified" do
        post :create, {:verified => valid_attributes}, valid_session
        response.should redirect_to(Verified.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved verified as @verified" do
        # Trigger the behavior that occurs when invalid params are submitted
        Verified.any_instance.stub(:save).and_return(false)
        post :create, {:verified => {}}, valid_session
        assigns(:verified).should be_a_new(Verified)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Verified.any_instance.stub(:save).and_return(false)
        post :create, {:verified => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested verified" do
        verified = Verified.create! valid_attributes
        # Assuming there are no other verifieds in the database, this
        # specifies that the Verified created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Verified.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => verified.to_param, :verified => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested verified as @verified" do
        verified = Verified.create! valid_attributes
        put :update, {:id => verified.to_param, :verified => valid_attributes}, valid_session
        assigns(:verified).should eq(verified)
      end

      it "redirects to the verified" do
        verified = Verified.create! valid_attributes
        put :update, {:id => verified.to_param, :verified => valid_attributes}, valid_session
        response.should redirect_to(verified)
      end
    end

    describe "with invalid params" do
      it "assigns the verified as @verified" do
        verified = Verified.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Verified.any_instance.stub(:save).and_return(false)
        put :update, {:id => verified.to_param, :verified => {}}, valid_session
        assigns(:verified).should eq(verified)
      end

      it "re-renders the 'edit' template" do
        verified = Verified.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Verified.any_instance.stub(:save).and_return(false)
        put :update, {:id => verified.to_param, :verified => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested verified" do
      verified = Verified.create! valid_attributes
      expect {
        delete :destroy, {:id => verified.to_param}, valid_session
      }.to change(Verified, :count).by(-1)
    end

    it "redirects to the verifieds list" do
      verified = Verified.create! valid_attributes
      delete :destroy, {:id => verified.to_param}, valid_session
      response.should redirect_to(verifieds_url)
    end
  end

end
